version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: momo-backend:local
    container_name: momo-backend
    ports:
      - "8081:8081"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8081/healthcheck"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: momo-frontend:local
    container_name: momo-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80/"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
