version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: momo-backend:local
    container_name: momo-backend
    ports:
      - "8081:8081"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8081/health"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VUE_APP_API_URL: "/api"
    image: momo-frontend:local
    container_name: momo-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
